baseurl = "https://example.com"
title = "Elastic Mint"
languageCode = "en-gb"
theme="hugo-universal-theme"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
publishdir = "../docs"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 1

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 3

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:jon@thinkexpedite.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "GBR"
    defaultKeywords = ["Elastic Mint", "hugo", "go"]
    defaultDescription = "Site powered by Elastic Mint using Hugo CMS"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCHysmrMKbu76mbHEktN3dztD6BpYJMV3Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "jon@thinkexpedite.com"

    about_us = "Our Story"
    copyright = "Copyright (c) 2018, Elastic Mint Ltd; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "Jan _2 2006"

    logo = "img/logo.png"
    address = """<p><strong>Elastic Mint</strong>
        <br>Bristol & Bath Science Park
        <br>Dirac Crescent
        <br>Emersons Green, Bristol
        <br>BS16 7FR
        <br>
        <strong>UK</strong>
      </p>
      """
    latitude = "51.500908"
    longitude = "-2.478331"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +44 0777 932 XXXX or info@elasticmint.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.ourstory]
    enable = true
    title = "Our Story"
    link_url = "/ourstory"
    link_text = "Read about how Elastic Mint came into being"

[params.values]
    enable = true
    title = "Our Values"
    subtitle = ""
    link_url = "/values"
    link_text = "Read about how our values shape the way we work"

[params.bios]
    enable = true
    title = "Who are we?"
    subtitle = ""


[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.news]
    enable = true
    icon = "fa fa-file-code-o"
    title = "News"
    subtitle = "What's happening with us....we will let u know when we have something to say"
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Client experiences"
    subtitle = "Collectively we have worked in the past with the following clients:"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""

